export const day =
    [
        { num: 1 },
        { num: 2 },
        { num: 3 },
        { num: 4 },
        { num: 5 },
        { num: 6 },
        { num: 7 },
        { num: 8 },
        { num: 9 },
        { num: 10 },
        { num: 11 },
        { num: 12 },
        { num: 13 },
        { num: 14 },
        { num: 15 },
        { num: 16 },
        { num: 17 },
        { num: 18 },
        { num: 19 },
        { num: 20 },
        { num: 21 },
        { num: 22 },
        { num: 23 },
        { num: 24 },
        { num: 25 },
        { num: 26 },
        { num: 27 },
        { num: 28 },
        { num: 29 },
        { num: 30 },
        { num: 31 },
    ]
export const month =
    [
        { id: 1, mes: "Enero" },
        { id: 2, mes: "Febrero" },
        { id: 3, mes: "Marzo" },
        { id: 4, mes: "Abril" },
        { id: 5, mes: "Mayo" },
        { id: 6, mes: "Junio" },
        { id: 7, mes: "Julio" },
        { id: 8, mes: "Agosto" },
        { id: 9, mes: "Septiembre" },
        { id: 10, mes: "Octubre" },
        { id: 11, mes: "Noviembre" },
        { id: 12, mes: "Diciembre" },
    ]
export const year =
    [
        { year: 1990 },
        { year: 1991 },
        { year: 1992 },
        { year: 1993 },
        { year: 1994 },
        { year: 1995 },
        { year: 1996 },
        { year: 1997 },
        { year: 1998 },
        { year: 1999 },
        { year: 2001 },
        { year: 2002 },
        { year: 2003 },
        { year: 2004 },
        { year: 2005 },
        { year: 2006 },
        { year: 2007 },
    ]